# Site Info
title:               Collection
tagline:             'Learning Path '
description:         'A collection of learning notes in computer science'
url:                  http://hchiuzhuo.github.io
baseurl:             '/blog'
paginate:            5
excerpt_separator:  '<!-- more -->'
#logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0


# About/contact
author:
  name:              Hsuan Chiu
  url:               https://hchiuzhuo.github.io/about/
  email:             cherylautumn@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://hchiuzhuo.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

